import { 
    YmButton , 
    YmIcon, 
    YmButtonGroup, 
    YmCollapse, 
    YmCollapseItem, 
    YmContextMenu ,
    YmAlert,
    YmTooltip,
    YmPopconfirm,
    YmDropdown,
    YmDropdownItem,
    YmCard,
    YmConfigProvider,
    YmMessage,
    YmNotification,
    YmInput,
    YmMessageBox,
    YmOverlay,
    YmLoading,
    YmSwitch,
    YmSelect,
    YmOption,
    YmForm,
    YmFormItem,
    YmProgress
} from '@ym-UI/components'
import type { Plugin } from 'vue'


export default [
    YmButtonGroup,
    YmButton,
    YmIcon,
    YmCollapse,
    YmCollapseItem,
    YmContextMenu,
    YmAlert,
    YmTooltip,
    YmPopconfirm,
    YmDropdown,
    YmDropdownItem,
    YmCard,
    YmConfigProvider,
    YmMessage,
    YmNotification,
    YmInput,
    YmMessageBox,
    YmOverlay,
    YmLoading,
    YmSwitch,
    YmSelect,
    YmOption,
    YmForm,
    YmFormItem,
    YmProgress
] as Plugin[]