<template>
  <ym-popconfirm 
    width="220"
    confirm-button-text="删除"
    cancel-button-text="不，取消"
    icon="trash"
    icon-color="#626aef"
    title="你确定要删除吗？"
    cancelButtonType="danger"
    confirmButtonType="primary"
  >
    <ym-button>Delete</ym-button>
  </ym-popconfirm>
</template>